### PR TITLE
Eliminate spurious PHP error messages: make logic run smoother

### PR DESCRIPTION
**Pull request by kn2tod**
Eliminate spurious PHP error messages; make logic run smoother

### CODE REVIEW

**Comment by kn2tod** [comment]
During initial configs, tons of spurious error messages issue from PHP because of improperly/partially defined variables: change IF statement nesting to correct

**Comment by MW0MWZ** [comment]
This page is not called during the initial config, not sure where that comes, from, but the change looks sane.

**Comment by kn2tod** [comment]
Errors show up when you enter the Config panel multiple times and options like the "modem" selection have not been made yet.   Thanks!

**Comment by MW0MWZ** [comment]
OK, I'll have a look at those.

**Review by kn2tod — COMMENTED** [review]
thanks

**Pull request merged**
