### PR TITLE
Fixed tooltips on config title fields and callsign in titles.

### PR DESCRIPTION
**Pull request by JDogHerman**
- Titles on some pages were M1ABC rather than the proper set callsign.
- Tooltips on the config page in 'td' were being obscured 
- Spacing issues fixed to match rest of styling.

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
If the title is M1ABC - you just need to press apply on the main config page - this is not a code issue.
All of the rest of the changes included are formatting changes without changing the code.

**Comment by JDogHerman** [comment]
@AndyTaylorTweet Why is the callsign stored in 2 places?

The rest are formatting changes that improved the readability of the code and the ability of the tooltip on the config page. Previously the tool tips were being hidden within the table cell.

**Comment by AndyTaylorTweet** [comment]
The callsign is stored in a bunch of places, but it can be stored in different formats - I make sure the pages pull it from a source where it will only ever me a bare callsign.

**Comment by AndyTaylorTweet** [comment]
I need to spend some time looking at the removal of the overflow hidden option - I did that to cure a specific issue.... that I may have since cured in other ways...

**Comment by JDogHerman** [comment]
What would you think of a help page that could be used to provide more details about each field? That way rather than hyperlinking to the existing page at the main anchor it could open a new window (a help page) that could have an anchor tag at each topic.

@AndyTaylorTweet if you like that idea I could create another pull request with it added. Thoughts?

**Comment by JDogHerman** [comment]
When a git pull is preformed on the local repo for the dashboard the callsign is reset to M1ABC rather than using the current config set callsign. The pull request bypasses this by using the current config callsign that is persistent with the running config.

**Comment by AndyTaylorTweet** [comment]
Git reset will do that for sure, but a git pull doesn't.

**Comment by AndyTaylorTweet** [comment]
Can you split the pull up for me - submit the formatting code on its own without the changes to the hostname or the changes relating to the tooltips, that set can then be merged in.

I somewhat agree on the hostname code - the config line may be irrelevant now (it has some old roots) but I want to investigate that fully and then possibly totally pull it out.

I already merged your change for MOTD - thats pretty good, although I may want to modify it to include the "http://" in the match / replacement to make very sure only the correct part of the file is modified - but that can wait....

**Comment by AndyTaylorTweet** [comment]
While I think about it - I am interested in the fix for the tooltips, I'm not ruling it out - but want to test it first.

**Comment by JDogHerman** [comment]
Yes, Ill will break these into 2 separate pullreqs.

**Comment by AndyTaylorTweet** [comment]
A new PR has fixed this up: https://github.com/AndyTaylorTweet/Pi-Star_DV_Dash/pull/66

**Pull request closed without merging**
