### PR TITLE
Fix for YSF Network status is not corretly displayed

### PR DESCRIPTION
**Pull request by yngwiechou**
Hello Andy,

Found the issue is actually in the "switch" section.

Regards,
Yngwie

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
Can you tell me what issue you are seeing before this patch is applied?

**Comment by yngwiechou** [comment]
Hi Andy,

To reproduce the issue, you can set the YSF reflector to none.
In this case, the YSF Network section on dashboard should be "not linked", however it remains the last YSF reflector.

Regards,
Yngwie

**Comment by yngwiechou** [comment]
Hi Andy,

I: 2018-02-14 09:02:31.371 The ID of this repeater is 84392
M: 2018-02-14 09:02:31.381 Automatic connection to 00325 - "TW YSF886       " <---- Entry 3
M: 2018-02-14 09:02:31.382 Starting YSFGateway-20170719  <---- Entry 2
M: 2018-02-14 09:02:31.382 Starting the APRS Writer thread
M: 2018-02-14 09:02:31.638 Connected to the APRS server
I: 2018-02-14 09:03:05.867 The ID of this repeater is 84392
M: 2018-02-14 09:03:05.875 Starting YSFGateway-20170719  <---- Entry 1
M: 2018-02-14 09:03:05.875 Starting the APRS Writer thread
M: 2018-02-14 09:03:06.202 Connected to the APRS server

After Entry 1, YSF reflector is set as "none".

The first issue is:

In the foreach loop (line 626), the $to is reset as "" empty string everytime (line 628), until it catch Entry 3, which is a previous YSF connection.

The second issue is:

line 646 and 649:

```
           return "not linked";
            break;
    } else {
            return "Service Not Started";
            break;
    }
```

More than one break is used in the switch section, that will cause problems (compilation?) even we fix the first issue.

I hope this explains the problem.

Regards,
Yngwie

**Comment by AndyTaylorTweet** [comment]
Yes it does - reproduced that here now, surprised I didn't see this sooner...

**Pull request merged**
