### PR TITLE
Dashboard v20181018 - Added DAPNET/POCSAG Status Information to Dashboard

### PR DESCRIPTION
**Pull request by geeks4hire**
Hi Andy,

Please consider the following additions to the Pi-Star Dashboard. Your feedback is very welcome. I am working with an Australian team implementing POCSAG/DAPNET within our country, and am trying to contribute code back to the software authors without which our goal would be an impossibility. A few other DAPNET/POCSAG related TODO's and ideas yet to come, but as of the below commit, the changes are self-contained and testing well.

Kind regards,

Ben Horan

```
- Added DAPNETGateway to System Status bar at top of page (replaced "Timer")
- Added POCSAG and POCSAG Network Status blocks to Services / Network Sidebar status information
- Added POCSAG Specific section to bottom of sidebar, indicating Callsign, Transmission Freq, and Whitelisted RIC's (if ANY)
- Updated version.php to reflect most recent change to code as of current date

- TODO:  Finish function in /mmdvmhost/functions.php that will parse DAPNETGateway log files for recent RICs and Message Contents
- TODO:  Produce a table below "Local RF Activity" that shows recent POCSAG Transmissions via the Hotspot (or repeater) - IF POCSAG is Enabled and running.
```

### CODE REVIEW

**Comment by geeks4hire** [comment]
pistar_dashboard_with_dapnet_pocsag-v20181018_by_bjh--admin_page-1
pistar_dashboard_with_dapnet_pocsag-v20181018_by_bjh--dashboard_page-1

_Note: Colour change is not hardcoded - I've simply changed the CSS colour values in the Config as you've designed the Dashboard to be visually 'tweaked'..._

**Comment by geeks4hire** [comment]
Additional changes and version bump to dashboard. List of changes below.  These commits represent the main work of bringing status and activity visibility of POCSAG/DAPNET into the Pi-Star Dashboard UI. 

A couple of future TODO's re: Internationalisation, moving DAPNET server list to stand-alone file (rather than being hard-coded in massive "configure.php", and adding ability to send POCSAG message via REST API calls (similar to being able to drop TG's and other Brandmeister functions from the Admin screen if Pi-Star Dashboard is provided the credentials).

```
- FIXED:  Sidebar for Service, Network Status, etc - tidied up code logic for POCSAG related sections added in last commit

- ADDED:  DAPNETGateway log parsing - extracts transmitted message info for display
- ADDED:  New File "/mmdvmhost/dapnetTx.php" to display Dashboard table of POCSAG Transmitter activity
          (only visible if POCSAG mode is Enabled and DAPNETGateway Active)

- TODO:   Add Internationalisation code to labels and headers of new information display. Ascertain whether there are contributors
          from different nationalities that can check the Language Pack file entries for each language is correct word/spelling
          (otherwise - Google Translate to build up base translations??)

- TODO:   Add include to "/mmdvmhost/functions.php" to "/index.php" so that config items can be ascertained (place the Ajax script
          and PHP include for "dapnetTx.php" table in a conditional so that rather than "dapnetTx.php" simply returning no visible
          HTML if POCSAG isn't disabled, have it so that "index.php" doesn't reference it (or Ajax refresh it every 1500ms) at all!
```

**Comment by geeks4hire** [comment]
Final look for dashboard POCSAG / DAPNET configured and active Pi-Star system (note: colour change from red is NOT hardcoded anywhere - simply a CSS preference I entered in Expert settings for my own hotspot  :+1: ) 

pistar_dashboard_with_dapnet_pocsag-v20181020_by_bjh--admin_page-2

**Comment by geeks4hire** [comment]
Hi Andy,

Thanks for your feedback... The reason for providing the message log is multi-factorial:

1. The community are already working on bringing this out on Nextion displays etc by means of NextionDriver extensions

1. It's amateur radio - and nothing about the POCSAG service is private or even implied private at any point. It can be plucked off the air and decoded, or it can simply be viewed in the log file on the hotspot.

As for supporting more master servers and in a more user friendly way, I'm afraid this will be unavoidable. DAPNET's core team holds the attitude "it's your problem to comply with local laws", and approve anything and everything. There's no validation on message data, no mandatory callsigns identifying senders (you can simply delete it from the textbox), etc... Also, by default, every message that someone creates via Web or App default to the worldwide "all' transmitter group unnecessarily.

Put simply, I understand why Italy had to go solo. To comply with our local regulations, we need to implement our own Master Server as well and ensure the system complies to the behaviour demanded by law here. It's unfortunate that DAPNET v2.0 seems to have been shelved (going by code commits) and DAPNET v1.x keeps getting patched to limp along, when there was a significant and worthwhile re-think in the way they were to do the architecture in v2.0 that's smarter, cleaner, and more scalable.... 

It could be that inter-master message routing could become a thing based on callsign prefixes wouldn't be too difficult to build up to bridge Masters *shrugs*, but the inability to obtain delegated administration to a national level, plus the "your laws aren't our problem, even if our actions are causing the problems" response from Germany - it does make sense to actually "decentralise" - in fact for countries such as AUS (and I suspect, Italy), it's necessary for us to lawfully implement POCSAG using DAPNET.... 

Having national Master servers that can manage their own users/transmitters etc and still exchange messages with international recipients would actually make DAPNET "Decentralised" for the first time, as opposed to the current situation of  "one German server is the single point of failure for the vast majority of transmitters" (aka both a "centralised" and "SPOF" approach presently ironically) since the release of Pi-Star 3.4.16 included DAPNETGateway worldwide.

Please feel free to use whatever of the submitted code you like.... I hope that it rounds out the POCSAG visibility in the Dashboard (I realise it's the latest service to be added to Pi-Star, so just trying to be helpful).

I try not to be the type that identifies a problem or an opportunity for enhancement without making the effort to also try and provide the grunt work to move things along - rather than just griping in FB channels, or expecting the original authors/maintainers to find the time to code a fix or feature just because someone on the other side of the world demanded it... I don't see that as the spirit of programming or Amateur Radio...

I'll keep an eye on repository updates, but please feel free to get keep touch!

Cheers,

Ben

**Comment by AndyTaylorTweet** [comment]
Ben,

I agree on point 1 and 2 - just still on the fence; I'll think about that some more.

On the masters front, that's not somthing I had given that much thought to - and I can now totally see your point; I'll work that in too.

Andy

**Comment by geeks4hire** [comment]
Thanks Andy, 

There’s probably more to disclose about why I’d go to so much effort to parse our the DAPNET Logs and make them presentable:  the new function that MMDVM / Pi-Star has in being the basis for the future wide-range transmitters (MMDVM Repeater boards connected to say a used Motorola GM3xx or CDM750 gives you a very simple 40watt Transmitter with a clean RF output. This is why Nextion enthusiasts are looking at implementing the equivalent of the DMR “last calls list” screen, but with POCSAG msgs passing through the system.

Due to the still unfathomable fact that Germany’s web interface and Android app default to sending every message anyone composed out to every transmitter (personal and wide range) in the entire system unless the Transmitter Group defaulted to “all” is manually changed to at least selective of the country of the recipient, then a PiStar hotspot with POCSAG enabled goes NUTS unless the user implements their own pager RICs in the Whitelist setting... In this case, the only messages they’ll see logged are messages to pager RICs they have a direct connection to (the screenshot I’ve submitted above shows a typical scenario there - that’s why I chose to include whitelist RICs in the sidebar info..

So two very different user types can use POCSAG on Pi-Star - one will have it like either as part of a digital voice Repeater or a dedicated Paging transmitter where all other voice modes are disabled on the unit. The second user (the home user) uses the hotspot to either experiment with Paging, or to compensate for coverage gaps. As they won’t want their Hotspot madly trying to deliver a worldwide queue of DAPNET messages using their measly 10mW’s of RF power, they’re very likely to set up their whitelist quickly. In both scenarios, having the message log available is neither “peeping tom”, or an invasion of Privacy (as we’ve established, anything sent in the open over airwaves unencrypted isn’t aimed at being secret or private (in fact secret or obfuscated messages are illegal on the amateur band (I believe this is a common internationally shared regulation). 

You could add a toggle and an entry in the MMDVMHost config file that defaults to off, but I would highly recommend you Survey the “POCSAG over MMDVM” Facebook group to ascertain interest in this feature being at least available to switch on, and the uses people may have - I doubt they’ll weigh up as nefarious... People disclose more in their QRZ profiles, and we think nothing of making them clickable links... 

The other argument is “I’m responsible for the transmissions from my device - I have a right to know what they are”... That comes into play when DAPNET easily send out msgs with no sender callsigns (a transmission with no ID in almost any emission mode in AUS is illegal)... 

If you have a pager, let me know your callsign and country, and i’ll send a demo of one of a long list of regulatory compliance headaches that come down to poor programming (eg: accepting unvalidated, non-sanitised posts to a REST API and placing your “business logic” or security in a JavaScript web app running in a persons browser). I wouldn’t send such a demonstration message to “all” as I’d then be causing AUS transmitters currently linked to Germany to transmit a callsign-absent message... 

I hope that makes a bit more sense - the two audiences intended for that activity table are: 1) Repeater / Wide-Range POCSAG transmitter operator using PiStar and MMDVM (because unless Germany ever finishes the reworked v2.0 of DAPNET which seems to have seen zero new code in 4 months, using the DAPNETGateway daemon embedded in Pi-Star’s bundle is actually the most straightforward way to hook into DAPNET with your transmitter ironically - especially as there is a ban on any more v1.x “nodes” being added (change freeze pending v2.0, but 2.0 has stalled).

I hope you’ll be happy to provide the activity log as an option to users in Pi-Star’s dashboard. Though it’s much much more of a maintenance headache, if you have any concerns ala privacy etc, I can maintain a fork of the Dashboard for users that seek the added POCSAG info and message table (that they can make the choice to clone)  - it just means I need to keep merging your future changes (and of course, “custom” things get clobbered every time a user clicks the Update link in the Dashboard header, etc) - I’d very much like to hopefully present the reasons, rationales, uses and merits for why I’ve created the specific POCSAG-related code additions that I have, and for you to feel comfortable with them becoming part of the main codebase for the Dashboard (of course, I’m open to compromise ideas such as toggle-option for the activity table that’s off by default - those that will find great usefulness in the near real-time message log can easily find out how to enable the feature, if its available to enable). DAPNET’s core team go to great lengths to highlight that DAPNET Paging is NOT private in any way. It’s great for automating weather alerts, radio club net announcements, or short banter of the same likes you would hear on air by linking to a Brandmeister TG. It’s most certainly not for sending passwords, or arranging adulterous affair liaisons lol. In the spirit of “everything in Amateur Radio is open”, I hope you’ll grow to feel comfortable with the message activity log table.

Does all of that reasoning make sense from your perspective (you’re allowed to tell me off for rambling lol)?

Please let me know if you have any other questions, concerns or critiques - I’m glad we’ve now got an open line of communications open!

Thank you for discussing your concerns and for taking into consideration my rationales/motivations!

Cheers,

Ben

**Comment by geeks4hire** [comment]
PS: If you’d like to use this image as a sample, or like me to gather & collate user feedback on the for’s/against’s and responses to this as a mock-up of a “possible future” Pi-Star Dashboard, please let me know - only too happy to... 😉 

7b1c68d3-f13c-4c78-add4-077375cf014d

**Comment by AndyTaylorTweet** [comment]
Ben,

Using some of your ideas here already, and making some twists myself; should see some useful changes to the dash over the next few days... So keep an eye out for that.

I've already setup the functions.php for collecting the log entries from the DAPNETGateway log although I still have some work to do on that too.

I appreciate your work - even if I dont use it exactly as presented, and it's given me a kick to go and get on with it - so thats all good :)

Andy

**Comment by geeks4hire** [comment]
Thanks Andy - I'll wait and see what pops up in the repository... LOL.... Look forward to seeing what you've been "inspired" to produce! :laughing: 

As a PS:  Do you have a line of communications with Jonathan Naylor (MMDVMHost, MMDVM firmware, and almost everything else that makes Pi-Star and an MMDVM board the ubiquitous hotspot loaded with features lol)? There is one _tiny_ feature that I'm aiming to get into DAPNETGateway, and it's based on code that Jonathan has written pretty much all the code for already - he's already able to send timed Station CwID's (but on the voice frequency via MMDVMHost, not the POCSAG frequency [which I believe has a rudimentary "station ID announcer" in DAPNETGateway, but it only sends in a POCSAG encoded message)... 

I can see he's written CwID into the MMDVM firmware, he's written it into the MMDVMHost code, and he's got a similar timer function running in DAPNETGateway that sends a station ID (of sorts) in a POCSAG message addressed to RIC "0000008" at least once every 10 mins... 

In the interests of winning over some of the "anti-digital brigade" of local HAMs (surely these folks aren't unique to Australia?? lol), we're hoping to have DAPNETGateway able via a config file setting to send the Station ID callsign in either POCSAG msg (as it does now) or in CW morse (as is already implemented on the Voice frequency as an option - code's all written there)... 

I estimate that it would take Jonathan extremely little time as he's written 95%+ of the code needed, and he knows how all his components link via MMDVMHost to the MMDVM firmware on the STM32 micro to the ADF7021, etc... 

As my C++ skills are rusty to say the least, this is one feature that I believe might be very quickly added by the guru of the code himself - but as I've already said - I really do try to put in work myself when people share their projects for us to benefit from, rather than imposing the expectation on the creator to solve my problems with their own time and effort. Sadly, in this instance, and with the coding essentially all-but written (just needing to be hooked into via the right timer in the right area of code), appealing to Jonathan is our best hope.

If you know Jonathan (and I'm guessing it'd be impossible to maintain the work you do without an excellent working relationship with the man), would you consider mentioning who I am, and that I'd just like the opportunity for a quick email or FB messenger chat to discuss this one feature for the POCSAG frequency on MMDVM Pi-Star's? 

I'd be extremely grateful of the opportunity to engage a conversation with Jonathan (and having the DAPNETGateway transmit on POCSAG frequency a station identify in CW rather than in POCSAG where there's a very large negative for other radio users which is "if you don't know what this 'special POCSAG RIC address' is for, or you don't know that the FSK modulated digital data is in POCSAG format so that you can obtain the software to decode it, then you're going to have a LOT of work on your hands simply identifying whose signal you're picking up" - vs morse, which everyone is used to and can be readily understood or decoded with no knowledge of the transmission signal type... 

The POCSAG transmission with a callsign might slip through as *just* meeting the requirement for Station ID broadcasts in Digital Mode at least every 10 mins via a grey area of regulations (they may be wider open in other countries, but here, using POCSAG for Station ID callsigns is both a "grey area" of legitimacy, and comparatively quite unfriendly when compared with CW..., We won't cop any grief while we're only piping those POCSAG transmissions out to a stubby antenna at 10mW, but we may well be challenged here in AUS as we deployed higher-power transmitters - if somebody complained to the Government Regulator, but as the whole Amateur Radio community is used to CW station ID's on FM analog repeaters (hell, even Pi-Star can be configured to send it out regularly on the voice frequency for ready-to-go use on Digital Voice Repeaters using Pi-Star and an MMDVM board [ala the POCSAG Transmitter scenario I mentioned earlier, which is an almost identical setup lol]), it'll go down a LOT smoother with the community if I can manage to get this feature configurable and enabled on transmitters BEFORE we go 'wide-range" with our deployment plans (and get some super familiar morse on the airwaves to save our skins).

Sorry for the lengthy begging email (it's approaching the time of night where my brain has already taken itself to bed, yet my fingers remain hovering over the computer keyboard lol), but I've been trying to find an open avenue of communications with Jonathan, and the best I've managed to do is raise a GitHub issue on the DAPNETGateway repo (which is soooooo not the way I wanted to ask "the guru of MMDVM" to please consider a tiny feature add from existing code, explain the reason why it's such a simple but valuable feature, and as the leader of the project team implementing DAPNET/POCSAG paging in Australia, how much of a huge win this would be for us (and I'm sure we're not the only ones!). 

I'd try and submit a push request with an "attempted code patch" in the interests of 'good will'/making an effort, but frankly I think Jonathan would waste more time looking at my clumsy C++ hacking of one of his pet projects than it'd take him to actually enable the desired feature in code himself lol...

So any help you could offer (if you can offer any) would be greatly appreciated! 

Even if you were willing to copy/paste this fairly rambling comment post into a medium that Jonathan could see it, and mention that I'm contactable directly via email at:  <benh@geeksforhire.com.au>, I'd be willing to discuss your bribe level lol...

Cheers for reading this far...

-Ben

**Comment by AndyTaylorTweet** [comment]
One solution for you - is to run an independent radio with MMDVM and POCSAG on the same TX frequency, that should then send the ID with CW - and POCSAG - but yeah, does mean another radio...

added most of the dashboard additions for POCSAG now, no network status yet - but I'll add that soon too.

**Comment by geeks4hire** [comment]
Nice idea but won't work... DAPNET has TimeSlots assigned to transmitters that they must obey (PS: hotspots need to be NTP-Sync enabled by default too with DAPNET - there's a config setting to consider adding!!)... As all transmitters use the same freq, nearby Tx's can't send at the same time... so all messages AND the station ID need to be timed to be sent out within those timeslot allocations... Can't be done anywhere but where it's currently coded to send POCSAG... And the code's there to send CW instead... Literally "read value of config file, if 'POCSAG', call this method, if "CW", call this method" is the extent of the changes. Definitely doesn't warrant 2nd radios - just the most minor change in software. For those that don't care about it (just like CW on voice which is disabled by default), it's no biggie, but for those that do need it, being able to enable CW is a HUGE thing for 10 mins coding from the guru who knows the code backwards... *sigh*....

Cliquey little groups in Amatuer Radio / Software... The core DAPNET team are a nightmare to liase with (both their coding and their attiudes), and Jonathan Naylor's doing a great job of ghosting...

Why the hell do we bother making this stuff open and sharing / contributing to aid each others work? I'm seriously starting to wonder....

Anyway, closing this pull request to untie you from my *master* branch of the repo fork. Was supposed to be tied to a "20181020" standalone branch for those changes, and I've got more work to do in my local repo...

Nice collaborating with you Andy! I'm sure our paths will cross again... 

Cheers!

**Comment by AndyTaylorTweet** [comment]
The CWID on a separate radio should work - it should work because MMDVMHost can be told to output the callsign every 10 mins in CW; when using MMDVM and DAPNetGW the traffic from DAPNetGW is only passed when MMDVMHost is idle - so in theory at least, you will still be getting the CW ID.

The problem with the current setup, is the QSY, send pages, QSY back, because in doing that, so far as I know - no ID goes out on the pager frequency (this is why I suggested setting up a separate MMDVMHost/DAPNetGW system - on one single frequency - so that the CWID goes out while idle - make sense ?

I agree that the timing matters, however in the UK at least, the only pager we can get that works on a frequency we can legally use - also understands duplicate pages, and can be told to ignore them.

Not sure how much all of that helps you, but those are my thoughts anyway.

As you will have noticed, my version of the POCSAG Data isn't as complete as yours, I don't have the RIC list for example, rather than the RIC list, I'm going to add a line notice on the dashboard to say if the pages are filtered or not - because that RIC list *could* be huge on some installs - you might have 50 locals that you want to service and drop all of the other nations crap for example - so who knows.

**Pull request closed without merging**
