### PR TITLE
Fix hardcoded HTTP calls

### PR DESCRIPTION
**Pull request by bilson**
When proxy reverse with SSL is used, javascript is not loaded.
Updated form action urls.
Aded jquery-timing.min.js to repository because always load from http site.

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
I can see the thinking here, but this would break for anyone serving https directly from the Pi, this is why the http/https is missing from the request.

**Comment by bilson** [comment]
Now if users add https directly in the raspberry don't works, because calls to javascript are without https and browser don't load this files. With this changes works with https directly in raspberry and with reverse proxy :)

**Comment by AndyTaylorTweet** [comment]
I'm working on finding / replacing these with sed and then re-committing them, this PR be pull-able once I am done - but doing it this way means I should not miss any.
Already fixed all of the forms...

**Comment by AndyTaylorTweet** [comment]
OK all done, that should do it - please test it, and drop this PR if its OK.

**Comment by bilson** [comment]
Hi,

All changes works, except by the jquery-timing.min.js script. Always load from http. It's why I add the file to repository instead of call remote.

image

I'll close my PR. Thanks for your work :)

**Comment by AndyTaylorTweet** [comment]
I'll pull that in later on today

**Pull request closed without merging**
