### PR TITLE
Add support for Hotspot ID:

### PR DESCRIPTION
**Pull request by f1rmb**
- Adding an extra digit to the CCS7 permits to have more than one hotspot connected to BM or DMR+. DMR+ allows ten hotspots (0 to 9), BM allows hundred (00 to 99).   - Since BM and DMR+ share the config, it's limited to 10 hotspots.
   - Hotspot ID could be changed in General Configuration panel, value could be 0..9 or -1 (default) to don't use the hotspot ID feature. Value is stored in /etc/hotspot_id, and it's part of the backup/restore.
   - Hotspot ID parameter in General Configuration will only appears when DMRGateway is selected as the DMR Master.
   - URLs related to BM in DMR Configuration also take care of hotspot ID.
   - CCS7 + Hotspot ID are also used in bm link and bm manager.

If /etc/hotspot_id is missing, the code consider hotspot ID as -1 (disabled).

Lang files: required entry has been added in all files, but translated in US, UK and FR only.

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
9 digit DMR IDs are already supported, I'm not sure I understand the point of this PR.

Please explain the problem you are actually trying to fix here.

**Comment by f1rmb** [comment]
You can't log on an XLX with such long CCS7, only on BM and DMR+. So, using DMRGateway is the correct solution, setting correct ID to Network 1 and 2.
About other systems (YSF and so on), I don't have any idea.

**Comment by AndyTaylorTweet** [comment]
Yes - and the dashboard already knows this.
Set your CCS7 to a 9 digit number and see what happens - networks that support them get the 9 digits, networks that don't only get 7 digits. I have already coded for that.

**Comment by f1rmb** [comment]
2 of my Ham friends already tried (DMR gateway, XLX, BM and DMR+), by just changing the "main" CCS7 with an extra digit. That let you outside the XLX server (all of using are using the XLX313, F module).

Cheers.

**Comment by f1rmb** [comment]
For the record, I'm using 3.4.17, not 4.0RC3.

**Comment by AndyTaylorTweet** [comment]
On the config page - set the CCS7 ID to a 9 digit number - (I run my own exactly this way) - DMRGateway is passed the 9 digit number from MMDVMHost - that number is used for DMR Network1, the other networks XLX/DMR Network 2 are configured (by the config page) with a 7 digit number that they use in preference.

There is no extra code required to make that work.

**Comment by AndyTaylorTweet** [comment]
It does not matter - 3.4.x and 4.0.x work the same

**Comment by f1rmb** [comment]
Question, when did you added this 7 or 9 CSS per master ?

**Comment by AndyTaylorTweet** [comment]
more than a year ago probably - its been there since VERY early on

**Comment by f1rmb** [comment]
Humm, weird. 
Few weeks ago, we where unable to connect XLX with CCS7 + 1, this is why we just added that extra digit to those ids in dmrgateway, to make it working...

**Comment by AndyTaylorTweet** [comment]
try using a 9 digit number, CCS7+01 - I'll go test the 8 digit to check..

**Comment by f1rmb** [comment]
I just checked 8 digits (using 0 ATM), it works (since DMR+ only accept 1 digit, as officially stated).

**Comment by AndyTaylorTweet** [comment]
Confirmed XLX and DMR+ are still truncated to 7 digits as they should be
If DMR+ now accept a single +1 digit - this is new - they didnt used to do that - so we've always truncated to 7 digits - I can ammend that - can you show me the announcement for the +1 digit support please...

**Comment by f1rmb** [comment]
Well, maybe the admins of XLX313 changed something in the last weeks, I don't know...

**Comment by AndyTaylorTweet** [comment]
XLX is always sent 7 digits - and currently DMR+ is also always sent 7 digits

**Comment by f1rmb** [comment]
Yes, let me dive my browser's history.

**Comment by f1rmb** [comment]
http://ipsc2fr.dnsalias.net/

Sorry, it's in french.

**Comment by f1rmb** [comment]
ATM, i'm using my patched version of PiStar, so it's sending CCS8 (Id is present in the dmrgateway section)

**Comment by AndyTaylorTweet** [comment]
It's not clear if that is just for France 3, or all of DMR+ so I am not going to modify the dashboard at this point unless you can find an announcement for all of the DMR+ masters.

**Comment by AndyTaylorTweet** [comment]
The stock version will send the whole 7/8/9 digits to the DMRGateway, so for testing you can edit DMRGateway by hand to change the DMR Network2 to add the extra digit - I am not going to accept or make changes for this until I understand what the scope is - just DMR+ FR3 or all of DMR+

**Comment by f1rmb** [comment]
Yeah, I know how to edit the IDs, since I'm doing that for quite some time, but we have some newbies here, and one they update the configuration using pistar, that resets the defined Ids.
Never mind, I understand that you don't want to apply that patch, I'll make some git mods on those hotspots.

Cheers.

**Comment by AndyTaylorTweet** [comment]
I think you are missing the point here, if you modify those hotspots - that will break their updates.
If this is a DMR+ wide change that effects all of DMR+, I will happily extend the IDs to 8 digits.

We have to do what is correct - not just a one-off.

**Comment by f1rmb** [comment]
I agree with you.
I'll just change the git remote url (and maybe few other things), until DMR+ network harmonize their policy about CCS7, 8 or 9 :-D

**Comment by AndyTaylorTweet** [comment]
Or you could maybe reach out to them to find out if it is a standard - I'm really not happy about divergent builds because the users still come to us for support - the dashboard is updated regularly - this is not a "fix"

**Comment by f1rmb** [comment]
I know Andy, but don't be afraid, I have no plan to fork PiStar, it's already a great tool that make user's life easier (I was used to install raspbian and G4KLX software by hand in the past).

Since many of us have more than one hotspot (e.g: one at home, one in the backbag), we need to be able to connect more than once from time to time, to the BM and/or DMR+ masters.

About support about local users, we are three to manage user's problems, none of them will contact you or submit an issue here. Few of them don't even know how to configure the PiStar. So, for them it's safe to have something "locked', even if they go to Configuration and press any "Apply" button (that will save time to my two friends and I).
Anyway, once the guys from DMR+ will "fix" their inconsistency about CSS, if will be easy to revert to official repositories of the PiStar.

Don't be surprised, I'll submit another small patch soon, just to be able to turn on/off BM when using DMRGateway, just like DMR+, instead of editing the file in expert mode (or with nano).

Cheers.

**Pull request closed without merging**
