### PR TITLE
Show TCXO frequency if applicable

### PR DESCRIPTION
**Pull request by phl0**
Should help people to identify their hardware ... :-)

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
Not sure that having this on the dash is the best place, but at the same time, I totally see that with the separate firmwares this really is a thing people need to know.

I suspect we also need to look at the flashing scripts to make them prompt the user too.

**Comment by phl0** [comment]
Roger that. I will try to implement a basic TCXO-check-before-flash.

**Comment by AndyTaylorTweet** [comment]
This broke quite comically on one of the modems here :) looking at that at the moment...

**Comment by phl0** [comment]
oO. With what result?

**Comment by AndyTaylorTweet** [comment]
Fixed, so if the log line didn't contain the TXCO frequency, it would return the whole log line, and that would splatter the section of the dashboard to fill the page, fun times.

Small mod made to look for the "MHz" string and only do something when it's there.

**Comment by phl0** [comment]
Shame on me. I should have checked it with other hardware :)

**Comment by AndyTaylorTweet** [comment]
I'm not in the slightest bit concerned :) Grateful for new ideas and PRs where the work is done for me :)

**Comment by phl0** [comment]
What do you think about these?

bildschirmfoto vom 2018-12-13 22-55-37


bildschirmfoto vom 2018-12-13 22-55-49

**Comment by AndyTaylorTweet** [comment]
That is kinda handy for guys who are running un-molested firmware from that actual source, but not all of it is, even some of the boards that are not clones of yours, don't all use Andy's builds exclusively, so its not really a thing I want to put on every dashboard.

Sadly we cant even have Andy put identifiers in the firmware, because other makers just clone the git without even bothering to read what they are looking at, its frustrating.....

**Comment by phl0** [comment]
Ah I see the point. I'll leave that out than.

**Comment by AndyTaylorTweet** [comment]
So - give me a few mins here, I think we can improve the flash script quite a bit... give me a few mins to come up with what I am thinking...

**Comment by phl0** [comment]
Sure.

**Comment by AndyTaylorTweet** [comment]
And now TCXO line added specifically too.
Now that those variable are present, I could modify the script to specifically ask the user if they really want to flash the wrong version if they select 12MHz code for 14MHz hardware :)

**Comment by phl0** [comment]
bildschirmfoto vom 2018-12-14 12-36-00

Looks fine. Would you also please merge https://github.com/AndyTaylorTweet/Pi-Star_Binaries_sbin/pull/28 ? It corrects some bad mistake in my downgrade script ....

**Comment by phl0** [comment]
Tnx :)

**Pull request merged**
